
name: Publish PR preview build to Docker Hub

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Start Containers
        run:
          docker compose -f demo/docker-compose-postman.yml up -d

      - name: Wait for index creation
        run: sleep 60s
        shell: bash

      - name: Run API test
        run: |
          postman collection run Tests/AzureSearchEmulator.postman_collection.json

      - name: Stop Containers
        if: always()
        run: |
          docker compose -f demo/docker-compose-postman.yml down

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src/SearchQueryService
          push: true
          tags: tomee/azure-search-emulator:${{ github.event.number }}-pr

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
